### PR TITLE
Few new footprints added

### PR DESCRIPTION
**Pull request by kajusK**
Hi,
so here are the new footprints for stepper drivers and Multiwat 15 package. Some rules from KiCad Library Convention confused me a little so I hope I have followed them correctly.

### CODE REVIEW

**Comment by CarlPoirier** [comment]
Hi,

Did you make sure the silkscreen outline is going to be completely visible
after assembly? This is rule 6.5. Also, please add the courtyard with
clearance of 0.25mm, as per rules 6.6 and 6.7. Finally, please set the
footprint anchor on pad 1.

Then, it should be good to go!

**Comment by kajusK** [comment]
Could you provide a link to some through hole package which meets this rules as a reference for me?

Well, these are the rules that confused me. I thought that silkscreen outline should match the package dimensions, therefore it should be right under the package edges after assembly. So I just made sure it won't overrun the pads.

The countryard with clearance, that's the area around the pad, correct? I though that '(clearance 0.25)' should match this requirement.

And about the anchor, well, almost all the footprints I saw before had footprint anchor in the center, which seems logical to me, but ok, I'll set it on pad 1.

How is the anchor handled when using the 3d packages? I made a DIP switch library (pull request is waiting in kicad-library) where footprints use the 3d models from unused_3d which all have the center in the middle. So I need to move all these models?

**Comment by kajusK** [comment]
Ok, here is a second try, I set the anchor on first pin, added reference mark and lines for 3d packages.

Could you please explain what you mean by incorrect clearance and how should I modify the silkscreen outline to match the rules? I still can't force myself to accept changing the outline to be visible instead of matching the package dimensions, who needs to see the silkscreen outline after assembling the board?

Thank you

**Comment by kajusK** [comment]
Just a note, the 3d packages pull request is waiting here KiCad/kicad-library#107

**Comment by CarlPoirier** [comment]
Hi Jakub,

The silkscreen outline should be visible to make post-assembly inspection
possible. Therefore it should be slightly larger than the package itself.
Place the silkscreen outline 0.125mm farther than the package dimensions,
so there would be a 0.05mm clearance between both. Please have a look at
the outline for LQFP-32 as an example. After assembly, we can still see the
four outline corners as well as the mark for pin one. BTW, such mark is not
necessary for your package because it cannot be placed in a wrong position.

As for the courtyard, it's the grey rectangle around the footprint, which
should be visible if you visualize that same LQFP-32_5x5mm_Pitch0.5mm in
pcbnew or in the footprint editor.

Finally, if your 3d model matches the footprint well, then it's alright.
I'll look at them once the footprints have been merged.

**Comment by kajusK** [comment]
Hi,
thank you for the clarification, I updated the footprints, is everything correct now?

**Comment by michal777** [comment]
Hi,
I've got some problem with opening this pull request in KiCad. When I go to:
https://github.com/kajusK/Power_Packages_ThroughHole.pretty
I can see only commit made by Carl (Parts moved from Pentawatts.pretty). If I switch branch to drivers, I can see the recent commits but the path:
https://github.com/kajusK/Power_Packages_ThroughHole.pretty/tree/drivers
can't be opened in KiCad. Is it possible to open this branch in KiCad or I must download it as zip?

**Comment by CarlPoirier** [comment]
I did have to download it. Jakub, it will be simpler next time if you
commit in the master branch of your repo.

**Comment by kajusK** [comment]
Well, right now, I've got two separated pull requests opened from the same repository, branches make this possible and easy to manage, if I had everything in the master branch, It would make a huge mess. Separated branches allow me to keep the master synchronized with the upstream while keeping my unpublished work unchanged.

But ok, I think I could push changes to the master branch next time.

**Comment by CarlPoirier** [comment]
Hi Jakub,

Can you use a dot, say with diameter 0.5mm, for indicating the pin one when necessary, and put the mark inside the courtyard? Everything is supposed to be contained in it. Also, the value and reference should be 1mm high. I think it will be good to go then.

I know these two things are not included in the KiCad Library Convention yet, but I'll look into adding them.

Thanks a bunch and sorry for the hassle.

**Comment by kajusK** [comment]
Hi Carl,
I changed the value and reference size, removed unnecessary  pin one marks or changed them to dot.

I hope everything is correct now.

**Comment by CarlPoirier** [comment]
Hi Jakub,

Are your pin 1 dots full? I see only a thin circle on my end. That also
applies to the DIP switches. It might be my KiCad, I'll update it whenever
I am back home.

**Comment by kajusK** [comment]
Hi Carl,
I wasn't sure how to add the full circle, so I added the graphic circle and modified the thickness to match the diameter...

**Comment by kajusK** [comment]
Hi Carl,
did you have some time to check it? Is there anything else I should change?

Thanks

**Comment by CarlPoirier** [comment]
Hi Jakub,

I do see a full circle now with an updated KiCad. I can merge it this way, unless you prefer to adopt a pin one mark like the one you did for the DIP switches.

**Comment by kajusK** [comment]
Hi Carl,
in this case I prefer a circle. And as mentioned in DIP switches pull request, I removed the clearance.

**Comment by michal777** [comment]
In SLA704XM the courtyard shouldn't be extended to be 0.25 mm from circle. There should be 0.25 mm measured from package body and pads, for additional graphics the clearance is nearly 0 mm (rounding 0.05, courtyard doesn't overlap silkscreen). In this case if the dot will be a bit closer to pin 1 it will be probably not necessary to extend courtyard.

**Comment by kajusK** [comment]
I didn't know that, ok, here's another commit.

**Comment by CarlPoirier** [comment]
Thanks Michal for the explanation.

It's great now! Thanks Jakub for your contribution.

**Pull request merged**
